### ISSUE TITLE
Fix Google API error message

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#26] opened 2018-08-21 02:08 UTC
When new server starts up this message pops up:

"Google API Error
Not a valid origin for the client: https://jupyter.ecocloud.org.au has not been whitelisted for client ID 625147942732-t30t8vnn43fl5mvg1qde5pl84603dr6s.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."

**Comment by gweis** [comment] 2018-08-21 03:06
duplicate of #4

**Closed as completed by gweis** 2018-08-21 03:06 UTC
