### ISSUE TITLE
Find fix for error that occurs when starting a new server

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#66] opened 2018-10-24 23:08 UTC
Have had a few messages come through from people saying there is an error.

This is the recurring error we get when trying to start a new server (see screenshot). I think we need to dedicate time to fixing this.

<img width="786" alt="screen shot 2018-10-25 at 9 07 10 am" src="https://user-images.githubusercontent.com/14067061/47466633-815ca980-d835-11e8-96b3-d0749485de13.png">

**Comment by gweis** [comment] 2018-10-24 23:12
duplicate of #27 ... fix is in the queue and will be deployed soon

**Closed as completed by gweis** 2018-10-24 23:12 UTC
